create or replace PACKAGE ORDER_MANAGEMENT AS

PROCEDURE CANCEL_ORDER(
CANCEL_OID ORDERS.ORDER_ID%TYPE);

PROCEDURE CANCEL_ORDER_ITEMS(
CANCEL_OPID ORDERPROD.ORDERPROD_ID%TYPE);

END ORDER_MANAGEMENT;
/

create or replace PACKAGE BODY ORDER_MANAGEMENT AS

PROCEDURE CANCEL_ORDER(
CANCEL_OID ORDERS.ORDER_ID%TYPE)
IS
BEGIN
DELETE ORDERS WHERE ORDER_ID = CANCEL_OID;

COMMIT;
END CANCEL_ORDER;

PROCEDURE CANCEL_ORDER_ITEMS(
CANCEL_OPID ORDERPROD.ORDERPROD_ID%TYPE)
IS
BEGIN
DELETE ORDERPROD WHERE ORDERPROD_ID = CANCEL_OPID;

COMMIT;
END CANCEL_ORDER_ITEMS;

END ORDER_MANAGEMENT;
/
